-- Create the common_code table
CREATE TABLE common_code (
    id bigint generated by default as identity primary key,
    created_at timestamptz default now() not null,
    category text not null,
    value text not null,
    description text,
    unique(category, value)
);

-- Add RLS (Row Level Security)
ALTER TABLE common_code ENABLE ROW LEVEL SECURITY;

-- Create policies for common_code
CREATE POLICY "Allow public read access" ON common_code
    FOR SELECT
    USING (true);


-- Add comments to the table and columns
COMMENT ON TABLE common_code IS 'Common codes for various categories used in the application.';
COMMENT ON COLUMN common_code.category IS 'Category of the code (e.g., INTERESTS, REGIONS, etc.).';
COMMENT ON COLUMN common_code.value IS 'The actual value of the code.';
COMMENT ON COLUMN common_code.description IS 'Optional description for the code.';

-- Insert predefined interests
INSERT INTO common_code (category, value, description)
VALUES
    ('INTERESTS', '오픈 AI', '오픈 AI 관련 토픽'),
    ('INTERESTS', '기술', 'IT, 과학 등 기술 관련 토픽'),
    ('INTERESTS', '테니스', '테니스 초보자 부터 윔블던 대회 참석자 까지 모두 모여있는 방'),
    ('INTERESTS', '고혈압', '혈압약을 끊고 싶은 사람들의 모임'),
    ('INTERESTS', '반려동물', '반려견,반려냥에 대해 고민하는 사람들의 모임'),
    ('INTERESTS', '성기능', '49금 고민으로 인한 사용자들의 모임'),
    ('INTERESTS', '탈모', '탈모로 고민중인 2570만 한국인을 위한 모임');
